return function()
    return {
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[11].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1605],
        workspace.Towers.CoLS.Obby:GetChildren()[1761],
        workspace.Towers.CoLS.Obby:GetChildren()[1760],
        workspace.Towers.CoLS.Obby:GetChildren()[1757], --F2
        workspace.Towers.CoLS.Obby:GetChildren()[1759],
        workspace.Towers.CoLS.Obby:GetChildren()[1758],
        workspace.Towers.CoLS.Obby:GetChildren()[1604],
        workspace.Towers.CoLS.Obby:GetChildren()[1598],
        workspace.Towers.CoLS.Obby:GetChildren()[1596],
        workspace.Towers.CoLS.Obby:GetChildren()[1594],
        workspace.Towers.CoLS.Obby:GetChildren()[1461],
        workspace.Towers.CoLS.Obby:GetChildren()[1459],
        workspace.Towers.CoLS.Obby:GetChildren()[1455],
        workspace.ClientParts.PushingPlatform:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1754],
        workspace.Towers.CoLS.Obby:GetChildren()[1586],
        workspace.Towers.CoLS.Obby:GetChildren()[1452], --F3
        workspace.Towers.CoLS.Obby:GetChildren()[1451],
        workspace.Towers.CoLS.Obby:GetChildren()[1449],
        workspace.Towers.CoLS.Obby:GetChildren()[1585],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[64]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1584],
        workspace.Towers.CoLS.Obby:GetChildren()[1583],
        workspace.ClientParts:GetChildren()[124].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1748],
        workspace.Towers.CoLS.Obby:GetChildren()[1747],
        workspace.Towers.CoLS.Obby:GetChildren()[1744],
        workspace.Towers.CoLS.Obby:GetChildren()[1742],
        workspace.Towers.CoLS.Obby:GetChildren()[1739],
        workspace.Towers.CoLS.Obby:GetChildren()[1733],
        workspace.Towers.CoLS.Obby:GetChildren()[1732],
        workspace.Towers.CoLS.Obby:GetChildren()[1731], --F4
        workspace.Towers.CoLS.Obby:GetChildren()[1726],
        workspace.Towers.CoLS.Obby:GetChildren()[1722],
        workspace.Towers.CoLS.Obby:GetChildren()[1721],
        workspace.Towers.CoLS.Obby:GetChildren()[1719],
        workspace.Towers.CoLS.Obby:GetChildren()[101],
        workspace.Towers.CoLS.Obby:GetChildren()[104],
        workspace.Towers.CoLS.Obby:GetChildren()[1582],
        workspace.Towers.CoLS.Obby:GetChildren()[1581],
        workspace.ClientParts:GetChildren()[123]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1447],
        workspace.Towers.CoLS.Obby:GetChildren()[1476],
        workspace.Towers.CoLS.Obby:GetChildren()[1714],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[45]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[71].Platform,
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[49]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[47]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects["Loose Platform"]:GetChildren()[2]
        

    }
end
