return function()
    return {
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[11].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1605],
        workspace.Towers.CoLS.Obby:GetChildren()[1761],
        workspace.Towers.CoLS.Obby:GetChildren()[1760],
        workspace.Towers.CoLS.Obby:GetChildren()[1757], --F2
        workspace.Towers.CoLS.Obby:GetChildren()[1759],
        workspace.Towers.CoLS.Obby:GetChildren()[1758],
        workspace.Towers.CoLS.Obby:GetChildren()[1604],
        workspace.Towers.CoLS.Obby:GetChildren()[1598],
        workspace.Towers.CoLS.Obby:GetChildren()[1596],
        workspace.Towers.CoLS.Obby:GetChildren()[1594],
        workspace.Towers.CoLS.Obby:GetChildren()[1461],
        workspace.Towers.CoLS.Obby:GetChildren()[1459],
        workspace.Towers.CoLS.Obby:GetChildren()[1455],
        workspace.ClientParts.PushingPlatform:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1754],
        workspace.Towers.CoLS.Obby:GetChildren()[1586],
        workspace.Towers.CoLS.Obby:GetChildren()[1452], --F3
        workspace.Towers.CoLS.Obby:GetChildren()[1451],
        workspace.Towers.CoLS.Obby:GetChildren()[1449],
        workspace.Towers.CoLS.Obby:GetChildren()[1585],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[64]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1584],
        workspace.Towers.CoLS.Obby:GetChildren()[1583],
        workspace.ClientParts:GetChildren()[124].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1748],
        workspace.Towers.CoLS.Obby:GetChildren()[1747],
        workspace.Towers.CoLS.Obby:GetChildren()[1744],
        workspace.Towers.CoLS.Obby:GetChildren()[1742],
        workspace.Towers.CoLS.Obby:GetChildren()[1739],
        workspace.Towers.CoLS.Obby:GetChildren()[1733],
        workspace.Towers.CoLS.Obby:GetChildren()[1732],
        workspace.Towers.CoLS.Obby:GetChildren()[1731], --F4
        workspace.Towers.CoLS.Obby:GetChildren()[1726],
        workspace.Towers.CoLS.Obby:GetChildren()[1722],
        workspace.Towers.CoLS.Obby:GetChildren()[1721],
        workspace.Towers.CoLS.Obby:GetChildren()[1719],
        workspace.Towers.CoLS.Obby:GetChildren()[101],
        workspace.Towers.CoLS.Obby:GetChildren()[104],
        workspace.Towers.CoLS.Obby:GetChildren()[1582],
        workspace.Towers.CoLS.Obby:GetChildren()[1581],
        workspace.ClientParts:GetChildren()[123]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1447],
        workspace.Towers.CoLS.Obby:GetChildren()[1476],
        workspace.Towers.CoLS.Obby:GetChildren()[1714],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[45]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[71].Platform,
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[49]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[47]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects["Loose Platform"]:GetChildren()[2],
        workspace.ClientParts:GetChildren()[78].Positions["1"],
        workspace.ClientParts:GetChildren()[78].Positions["2"],
        workspace.Towers.CoLS.Obby:GetChildren()[1766],
        workspace.Towers.CoLS.Obby:GetChildren()[1715],
        workspace.ClientParts:GetChildren()[64].Platform,
        workspace.ClientParts:GetChildren()[101].Platform,
        workspace.Towers.CoLS.Obby:GetChildren()[1577],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[63]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[66]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1580], --F5
        workspace.ClientParts:GetChildren()[49].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1444],
        workspace.Towers.CoLS.Obby:GetChildren()[1443],
        workspace.Towers.CoLS.Obby:GetChildren()[1441],
        workspace.Towers.CoLS.Obby:GetChildren()[1439],
        workspace.ClientParts:GetChildren()[11].Part,
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[67].Part,
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[66].Part,
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[63].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1481],
        workspace.ClientParts:GetChildren()[15].Part,
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[50]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1436],
        workspace.Towers.CoLS.Obby:GetChildren()[1436],
        workspace.Towers.CoLS.Obby:GetChildren()[1423],
        workspace.Towers.CoLS.Obby:GetChildren()[1421],
        workspace.Towers.CoLS.Obby:GetChildren()[1318],
        workspace.ClientParts:GetChildren()[46].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1414],
        workspace.Towers.CoLS.Obby:GetChildren()[1410],
        workspace.Towers.CoLS.Obby:GetChildren()[1595],
        workspace.Towers.CoLS.Obby:GetChildren()[177],
        workspace.ClientParts.MovingPlatform.MovingPlatform.Positions["4"],
        workspace.ClientParts.MovingPlatform.MovingPlatform.Positions["5"],
        workspace.Towers.CoLS.Obby:GetChildren()[180],
        workspace.Towers.CoLS.Obby:GetChildren()[840]:GetChildren()[20],
        workspace.Towers.CoLS.Obby:GetChildren()[840]:GetChildren()[12],
        workspace.Towers.CoLS.Obby:GetChildren()[835].LineSegment,
        workspace.Towers.CoLS.Obby:GetChildren()[835]:GetChildren()[9],
        workspace.ClientParts:GetChildren()[73]:GetChildren()[2],
        workspace.ClientParts.MovingPlatform.MovingPlatform.Positions["6"],
        workspace.Towers.CoLS.Obby:GetChildren()[1091],
        workspace.ClientParts:GetChildren()[127]:GetChildren()[3],
        workspace.Towers.CoLS.Obby:GetChildren()[1109],
        workspace.ClientParts:GetChildren()[17].Part,
        workspace.ClientParts.MovingPlatform.MovingPlatform.Positions["1"],
        workspace.Towers.CoLS.Obby:GetChildren()[1570],
        workspace.Towers.CoLS.Obby:GetChildren()[1568],
        workspace.ClientParts:GetChildren()[53].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1566],
        workspace.Towers.CoLS.Obby:GetChildren()[1404],
        workspace.Towers.CoLS.Obby:GetChildren()[1565],
        workspace.Towers.CoLS.Obby:GetChildren()[1553],
        workspace.Towers.CoLS.Obby:GetChildren()[1551],
        workspace.Towers.CoLS.Obby:GetChildren()[1407],
        workspace.Towers.CoLS.Obby:GetChildren()[1406],
        workspace.ClientParts:GetChildren()[57].Part,
        workspace.ClientParts.MovingPlatform:GetChildren()[2].Positions["5"],
        workspace.Towers.CoLS.Obby.SpeedBooster,
        workspace.Towers.CoLS.Obby:GetChildren()[226],
        workspace.Towers.CoLS.Obby:GetChildren()[227],
        workspace.Towers.CoLS.Obby:GetChildren()[230],
        workspace.Towers.CoLS.Obby:GetChildren()[234],
        workspace.Towers.CoLS.Obby:GetChildren()[232],
        workspace.Towers.CoLS.Obby:GetChildren()[231],
        workspace.Towers.CoLS.Obby:GetChildren()[237],
        workspace.Towers.CoLS.Obby:GetChildren()[239],
        workspace.Towers.CoLS.Obby:GetChildren()[279],
        workspace.Towers.CoLS.Obby:GetChildren()[235],
        workspace.Towers.CoLS.Obby:GetChildren()[1138],
        workspace.Towers.CoLS.Obby:GetChildren()[212],
        workspace.Towers.CoLS.Obby:GetChildren()[214],
        workspace.Towers.CoLS.Obby:GetChildren()[236],
        workspace.ClientParts.Button:GetChildren()[2],
        workspace.ClientParts.MovingPlatform:GetChildren()[2].Positions["6"],
        workspace.Towers.CoLS.Obby:GetChildren()[1174],
        workspace.Towers.CoLS.Obby:GetChildren()[1178],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[20],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[25],
        workspace.Towers.CoLS.Obby:GetChildren()[254],
        workspace.ClientParts:GetChildren()[16]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[255],
        workspace.Towers.CoLS.Obby:GetChildren()[256],
        workspace.Towers.CoLS.Obby:GetChildren()[258],
        workspace.Towers.CoLS.Obby:GetChildren()[1403],
        workspace.Towers.CoLS.Obby:GetChildren()[1655],
        workspace.Towers.CoLS.Obby:GetChildren()[263],
        workspace.Towers.CoLS.Obby:GetChildren()[264],
        workspace.Towers.CoLS.Obby:GetChildren()[265],
        workspace.Towers.CoLS.Obby:GetChildren()[1708],
        workspace.ClientParts:GetChildren()[22].Part,
        workspace.ClientParts.ButtonPlatforms:GetChildren()[90],
        workspace.Towers.CoLS.Obby:GetChildren()[1579],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[89],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[13],
        workspace.Towers.CoLS.Obby:GetChildren()[271], --F6
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[12].Platform,
        workspace.Towers.CoLS.Obby:GetChildren()[1402],
        workspace.ClientParts:GetChildren()[71].Positions["1"],
        workspace.ClientParts:GetChildren()[71].Positions["2"],
        workspace.Towers.CoLS.Obby:GetChildren()[280],
        workspace.Towers.CoLS.Obby:GetChildren()[284],
        workspace.Towers.CoLS.Obby:GetChildren()[288],
        workspace.Towers.CoLS.Obby:GetChildren()[292],
        workspace.Towers.CoLS.Obby:GetChildren()[332],
        workspace.Towers.CoLS.Obby:GetChildren()[340],
        workspace.ClientParts:GetChildren()[62]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[319],
        workspace.Towers.CoLS.Obby:GetChildren()[320],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[30],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[28],
        workspace.Towers.CoLS.Obby:GetChildren()[323],
        workspace.Towers.CoLS.Obby:GetChildren()[325],
        workspace.Towers.CoLS.Obby:GetChildren()[326],
        workspace.Towers.CoLS.Obby:GetChildren()[327],
        workspace.Towers.CoLS.Obby:GetChildren()[873],
        workspace.Towers.CoLS.Obby:GetChildren()[328],
        workspace.Towers.CoLS.Obby:GetChildren()[341],
        workspace.Towers.CoLS.Obby:GetChildren()[342],
        workspace.Towers.CoLS.Obby:GetChildren()[343],
        workspace.Towers.CoLS.Obby:GetChildren()[344],
        workspace.Towers.CoLS.Obby:GetChildren()[346],
        workspace.Towers.CoLS.Obby:GetChildren()[347],
        workspace.Towers.CoLS.Obby:GetChildren()[353],
        workspace.ClientParts:GetChildren()[58].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1313],
        workspace.ClientParts:GetChildren()[36].Part,
        workspace.ClientParts.ButtonPlatforms:GetChildren()[81],
        workspace.Towers.CoLS.Obby:GetChildren()[1309],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[19].Platform,
        workspace.ClientParts:GetChildren()[80].Platform,
        workspace.ClientParts:GetChildren()[63].Platform,
        workspace.ClientParts:GetChildren()[23].Platform,
        workspace.Towers.CoLS.Obby:GetChildren()[1467],
        workspace.Towers.CoLS.Obby:GetChildren()[1308],
        workspace.Towers.CoLS.Obby:GetChildren()[1307],
        workspace.Towers.CoLS.Obby:GetChildren()[1306],
        workspace.ClientParts:GetChildren()[118]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1385],
        workspace.Towers.CoLS.Obby:GetChildren()[1524],
        workspace.Towers.CoLS.Obby:GetChildren()[1699],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[44]:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[46].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1523],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[43].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1305],
        workspace.ClientParts:GetChildren()[120]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1303],
        workspace.ClientParts:GetChildren()[84].Positions["1"],
        workspace.ClientParts:GetChildren()[84].Positions["2"],
        workspace.Towers.CoLS.Obby:GetChildren()[1382],
        workspace.Towers.CoLS.Obby:GetChildren()[1381],
        workspace.ClientParts:GetChildren()[55].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1387],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[81],
        workspace.Towers.CoLS.Obby:GetChildren()[1386],
        workspace.Towers.CoLS.Obby:GetChildren()[1331],
        workspace.Towers.CoLS.Obby:GetChildren()[1313],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[83],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[79],
        workspace.Towers.CoLS.Frame.Basement1, --F7
        workspace.Towers.CoLS.Obby:GetChildren()[1399],
        workspace.Towers.CoLS.Obby:GetChildren()[1395],
        workspace.ClientParts:GetChildren()[121]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1398],
        workspace.Towers.CoLS.Obby:GetChildren()[1550],
        workspace.Towers.CoLS.Obby:GetChildren()[1545],
        workspace.Towers.CoLS.Obby:GetChildren()[1703],
        workspace.Towers.CoLS.Obby:GetChildren()[1696],
        workspace.Towers.CoLS.Obby:GetChildren()[1695],
        workspace.Towers.CoLS.Obby:GetChildren()[1518],
        workspace.ClientParts:GetChildren()[45],
        workspace.ClientParts:GetChildren()[85],
        workspace.Towers.CoLS.Obby:GetChildren()[1515],
        workspace.Towers.CoLS.Obby:GetChildren()[1379],
        workspace.Towers.CoLS.Obby:GetChildren()[1376],
        workspace.Towers.CoLS.Obby:GetChildren()[1370],
        workspace.Towers.CoLS.Obby:GetChildren()[1367],
        workspace.Towers.CoLS.Obby:GetChildren()[1366],
        workspace.Towers.CoLS.Obby:GetChildren()[1364],
        workspace.Towers.CoLS.Obby:GetChildren()[1462],
        workspace.ClientParts:GetChildren()[68].Platform,
        workspace.Towers.CoLS.Obby:GetChildren()[1640], --F8
        workspace.Towers.CoLS.Obby:GetChildren()[1688],
        workspace.Towers.CoLS.Obby:GetChildren()[1510],
        workspace.Towers.CoLS.Obby:GetChildren()[1363],
        workspace.Towers.CoLS.Obby:GetChildren()[1361],
        workspace.Towers.CoLS.Obby:GetChildren()[1357],
        workspace.ClientParts:GetChildren()[126]:GetChildren()[2],
        workspace.ClientParts:GetChildren()[119].Part,
        workspace.Towers.CoLS.Obby:GetChildren()[1503],
        workspace.Towers.CoLS.Obby:GetChildren()[842]:GetChildren()[17],
        workspace.Towers.CoLS.Obby:GetChildren()[1353],
        workspace.Towers.CoLS.Obby:GetChildren()[1351],
        workspace.Towers.CoLS.Obby:GetChildren()[1349],
        workspace.Towers.CoLS.Obby:GetChildren()[837]:GetChildren()[11],
        workspace.Towers.CoLS.Obby:GetChildren()[1501],
        workspace.Towers.CoLS.Obby:GetChildren()[843]:GetChildren()[11],
        workspace.Towers.CoLS.Obby:GetChildren()[1500],
        workspace.Towers.CoLS.Obby:GetChildren()[1675],
        workspace.Towers.CoLS.Obby:GetChildren()[1644],
        workspace.Towers.CoLS.Obby:GetChildren()[1679],
        workspace.Towers.CoLS.Obby:GetChildren()[1676],
        workspace.Towers.CoLS.Obby:GetChildren()[1492],
        workspace.Towers.CoLS.Obby:GetChildren()[1486],
        workspace.Towers.CoLS.Obby:GetChildren()[1493],
        workspace.Towers.CoLS.Frame:GetChildren()[152],
        workspace.ClientParts:GetChildren()[39].Part,
        workspace.Towers.CoLS.Frame:GetChildren()[191],
        workspace.Towers.CoLS.Obby:GetChildren()[1670],
        workspace.Towers.CoLS.Obby:GetChildren()[1669],
        workspace.Towers.CoLS.Obby:GetChildren()[1668],
        workspace.Towers.CoLS.Obby:GetChildren()[1666],
        workspace.Towers.CoLS.Obby:GetChildren()[1664],
        workspace.Towers.CoLS.Obby:GetChildren()[1663],
        workspace.Towers.CoLS.Frame:GetChildren()[193],
        workspace.ClientParts:GetChildren()[81].Positions["1"],
        workspace.ClientParts:GetChildren()[81].Positions["2"],
        workspace.Towers.CoLS.Frame:GetChildren()[188],
        workspace.Towers.CoLS.Frame:GetChildren()[181],
        workspace.Towers.CoLS.Obby:GetChildren()[1502],
        workspace.Towers.CoLS.Obby:GetChildren()[1485],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[21].Platform,
        workspace.ClientParts:GetChildren()[74].Positions["1"],
        workspace.ClientParts:GetChildren()[74].Positions["2"],
        workspace.ClientParts:GetChildren()[67].Platform,
        workspace.ClientParts:GetChildren()[69].Platform,
        workspace.Towers.CoLS.Obby:GetChildren()[1469],
        workspace.ClientParts:GetChildren()[125]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[1654],
        workspace.Towers.CoLS.Obby:GetChildren()[1658],
        workspace.Towers.CoLS.Obby:GetChildren()[1659],
        workspace.Towers.CoLS.Obby:GetChildren()[1660],
        workspace.ClientParts:GetChildren()[76].Positions["1"],
        workspace.ClientParts:GetChildren()[76].Positions["2"],
        workspace.ClientParts:GetChildren()[76].Positions["3"],
        workspace.ClientParts:GetChildren()[76].Positions["4"],
        workspace.ClientParts:GetChildren()[76].Positions["5"],
        workspace.Towers.CoLS.Obby:GetChildren()[614], --F9
        workspace.Towers.CoLS.Obby:GetChildren()[613],
        workspace.ClientParts:GetChildren()[44]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[624],
        workspace.Towers.CoLS.Obby:GetChildren()[626],
        workspace.Towers.CoLS.Obby:GetChildren()[627],
        workspace.Towers.CoLS.Obby:GetChildren()[628],
        workspace.Towers.CoLS.Obby:GetChildren()[630],
        workspace.Towers.CoLS.Obby:GetChildren()[631],
        workspace.Towers.CoLS.Obby:GetChildren()[632],
        workspace.Towers.CoLS.Obby:GetChildren()[625],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[38],
        workspace.ClientParts:GetChildren()[52]:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[72],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[41],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[70],
        workspace.ClientParts.ButtonPlatforms:GetChildren()[71],
        workspace.Towers.CoLS.Obby:GetChildren()[664],
        workspace.ClientParts:GetChildren()[50]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[670],
        workspace.Towers.CoLS.Obby:GetChildren()[685],
        workspace.Towers.CoLS.Obby:GetChildren()[693],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"].Spinner, --F10
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[18],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[20],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[23],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[26],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[28],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[29],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"].Part,
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[31],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[32],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]["Wobbly Plate"].ColorChangingPart,
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[35].ColorChangingPart,
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[36].ColorChangingPart,
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]["Spinning Platform"].Part,
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[40],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[48],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[49],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[39],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"].PushingPlatform:GetChildren()[2],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[55],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[56],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[57],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[58],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[60],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[61],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Platforms"]:GetChildren()[6],
        workspace.Towers.CoLS.Obby:GetChildren()[701],
        workspace.Towers.CoLS.Obby:GetChildren()[703],
        workspace.Towers.CoLS.Obby:GetChildren()[705],
        workspace.Towers.CoLS.Obby:GetChildren()[706],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[63],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[64],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[65],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[66],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[67],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[68],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[69],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[70],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[71],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[72],
        workspace.ClientParts.DistanceAnchoringObjects["Spinning Tower"]:GetChildren()[73],
        workspace.ClientParts:GetChildren()[116]:GetChildren()[2],
        workspace.Towers.CoLS.Obby:GetChildren()[707],
        workspace.ClientParts:GetChildren()[91]:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[23],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[25],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[27],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[28],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[30],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[31],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[33],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[34],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[37],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[38],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[40],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[48],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[49]:GetChildren()[6],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush.Curve.ButtonActivatedPlatform,
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush.Curve:GetChildren()[10],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush.Curve:GetChildren()[20],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[46]:GetChildren()[7],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[46]:GetChildren()[20],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[47]:GetChildren()[7],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[47]:GetChildren()[20],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[43],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[51],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[53],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[54],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[55],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[56],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[59],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[62],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[64],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[65],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[67],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[68],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[69],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[70],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[73],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[74],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[75],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[76],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[77],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[78],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[79],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[80],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[81],
        workspace.Towers.CoLS.Obby:GetChildren()[712],
        workspace.Towers.CoLS.Obby:GetChildren()[715],
        workspace.Towers.CoLS.Obby:GetChildren()[716], --F11
        workspace.Towers.CoLS.Obby:GetChildren()[719],
        workspace.Towers.CoLS.Obby:GetChildren()[720],
        workspace.Towers.CoLS.Obby:GetChildren()[724],
        workspace.Towers.CoLS.Obby:GetChildren()[725],
        workspace.ClientParts.DistanceAnchoringObjects["Wobbly Plate"].ColorChangingPart,
        workspace.ClientParts:GetChildren()[129].Platform,
        workspace.ClientParts:GetChildren()[128].Platform,
        workspace.Towers.CoLS.Obby:GetChildren()[727],
        workspace.Towers.CoLS.Obby:GetChildren()[854],
        workspace.Towers.CoLS.Obby:GetChildren()[856],
        workspace.ClientParts:GetChildren()[41]:GetChildren()[2],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[5],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[7],
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush.ButtonActivatedPlatform,
        workspace.ClientParts.ButtonPlatforms.F8ButtonRush:GetChildren()[4],
        workspace.Towers.CoLS.Obby:GetChildren()[731],
        workspace.Towers.CoLS.Obby:GetChildren()[732],
        workspace.Towers.CoLS.Obby:GetChildren()[734],
        workspace.Towers.CoLS.Obby:GetChildren()[735],
        workspace.Towers.CoLS.Obby:GetChildren()[737],
        workspace.Towers.CoLS.Obby:GetChildren()[738],
        workspace.Towers.CoLS.Obby:GetChildren()[739],
        workspace.Towers.CoLS.Obby:GetChildren()[740], --F12
        workspace.Towers.CoLS.Obby:GetChildren()[743],
        workspace.Towers.CoLS.Obby:GetChildren()[745],
        workspace.Towers.CoLS.Obby:GetChildren()[746],
        workspace.Towers.CoLS.Obby:GetChildren()[769],
        workspace.Towers.CoLS.Obby:GetChildren()[768],
        workspace.Towers.CoLS.Obby:GetChildren()[770]
        
    }
end
