return function()
    return {
        workspace.Towers.ToA.Obby:GetChildren()[14],
        workspace.Towers.ToA.Obby:GetChildren()[12],
        workspace.Towers.ToA.Obby:GetChildren()[59],
        workspace.Towers.ToA.Obby:GetChildren()[60],
        workspace.ClientParts.DistanceCulling:GetChildren()[13].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[63],
        workspace.Towers.ToA.Obby:GetChildren()[62],
        workspace.Towers.ToA.Obby:GetChildren()[68],
        workspace.Towers.ToA.Obby:GetChildren()[71],
        workspace.Towers.ToA.Obby:GetChildren()[69],
        workspace.Towers.ToA.Obby:GetChildren()[67],
        workspace.Towers.ToA.Obby:GetChildren()[77],
        workspace.Towers.ToA.Obby:GetChildren()[75],
        workspace.Towers.ToA.Obby:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[84],
        workspace.ClientParts.DistanceCulling:GetChildren()[10].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[11].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[90],
        workspace.Towers.ToA.Obby:GetChildren()[66],
        workspace.ClientParts:GetChildren()[79],
        workspace.ClientParts:GetChildren()[80],
        workspace.Towers.ToA.Obby:GetChildren()[97],
        workspace.Towers.ToA.Obby:GetChildren()[92],
        workspace.Towers.ToA.Obby:GetChildren()[98],
        workspace.Towers.ToA.Obby:GetChildren()[93],
        workspace.Towers.ToA.Obby:GetChildren()[91],
        workspace.Towers.ToA.Obby:GetChildren()[100],
        workspace.Towers.ToA.Obby:GetChildren()[101],
        workspace.Towers.ToA.Obby:GetChildren()[99],
        workspace.Towers.ToA.Obby:GetChildren()[111],
        workspace.Towers.ToA.Obby:GetChildren()[112],
        workspace.ClientParts:GetChildren()[81],
        workspace.ClientParts:GetChildren()[82],
        workspace.ClientParts:GetChildren()[83],
        workspace.Towers.ToA.Obby:GetChildren()[105],
        workspace.Towers.ToA.Obby:GetChildren()[113],
        workspace.Towers.ToA.Obby:GetChildren()[115],
        workspace.Towers.ToA.Obby:GetChildren()[116],
        workspace.Towers.ToA.Obby:GetChildren()[120],
        workspace.ClientParts.DistanceCulling:GetChildren()[14].Platform,
        workspace.ClientParts.DistanceCulling:GetChildren()[15].Platform,
        workspace.ClientParts:GetChildren()[84],
        workspace.Towers.ToA.Obby:GetChildren()[121],
        workspace.Towers.ToA.Obby:GetChildren()[122],
        workspace.Towers.ToA.Obby:GetChildren()[124],
        workspace.Towers.ToA.Obby:GetChildren()[128],
        workspace.Towers.ToA.Obby:GetChildren()[129],
        workspace.Towers.ToA.Obby:GetChildren()[130],
        workspace.Towers.ToA.Obby:GetChildren()[131],
        workspace.Towers.ToA.Obby:GetChildren()[72],
        workspace.Towers.ToA.Obby:GetChildren()[20],
        workspace.Towers.ToA.Obby:GetChildren()[132],
        workspace.Towers.ToA.Obby:GetChildren()[133],
        workspace.ClientParts.DistanceCulling:GetChildren()[17].Platform,
        workspace.Towers.ToA.Obby:GetChildren()[138],
        workspace.Towers.ToA.Obby:GetChildren()[140],
        workspace.Towers.ToA.Obby:GetChildren()[155],
        workspace.Towers.ToA.Obby:GetChildren()[153],
        workspace.Towers.ToA.Obby:GetChildren()[143]
        
        
        
        

    }
end
