return function()
    return {
        workspace.Towers.ToAST.Obby:GetChildren()[67],
        workspace.Towers.ToAST.Obby:GetChildren()[73],
        workspace.Towers.ToAST.Obby:GetChildren()[72],
        workspace.Towers.ToAST.Obby.Bridge:GetChildren()[22],
        workspace.Towers.ToAST.Obby:GetChildren()[75],
        workspace.Towers.ToAST.Obby:GetChildren()[112],
        workspace.Towers.ToAST.Obby:GetChildren()[105],
        workspace.Towers.ToAST.Obby:GetChildren()[108],
        workspace.Towers.ToAST.Obby:GetChildren()[115],
        workspace.Towers.ToAST.Obby:GetChildren()[114],
        workspace.Towers.ToAST.Obby:GetChildren()[161],
        workspace.Towers.ToAST.Obby:GetChildren()[157],
        workspace.Towers.ToAST.Obby:GetChildren()[150],
        workspace.Towers.ToAST.Obby:GetChildren()[155],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[49]["Kill Brick"],
        workspace.Towers.ToAST.Obby:GetChildren()[120],
        workspace.Towers.ToAST.Obby:GetChildren()[123],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[22].Part,
        workspace.Towers.ToAST.Obby:GetChildren()[125],
        workspace.Towers.ToAST.Obby:GetChildren()[135],
        workspace.Towers.ToAST.Obby:GetChildren()[126],
        workspace.Towers.ToAST.Obby:GetChildren()[127],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[26].Part,
        workspace.Towers.ToAST.Obby:GetChildren()[1019],
        workspace.Towers.ToAST.Obby:GetChildren()[1025],
        workspace.Towers.ToAST.Obby:GetChildren()[936],
        workspace.Towers.ToAST.Obby:GetChildren()[1031],
        workspace.Towers.ToAST.Obby:GetChildren()[224],
        
    }
end
