return function()
    return {
        workspace.Towers.ToAST.Obby:GetChildren()[67],
        workspace.Towers.ToAST.Obby:GetChildren()[183],
        workspace.Towers.ToAST.Obby.Bridge:GetChildren()[20],
        workspace.Towers.ToAST.Obby.Bridge.Part,
        workspace.Towers.ToAST.Obby:GetChildren()[112],
        workspace.Towers.ToAST.Obby:GetChildren()[104],
        workspace.Towers.ToAST.Obby:GetChildren()[108],
        workspace.Towers.ToAST.Obby:GetChildren()[114],
        workspace.Towers.ToAST.Obby:GetChildren()[111],
        workspace.Towers.ToAST.Obby:GetChildren()[157],
        workspace.Towers.ToAST.Obby:GetChildren()[150],
        workspace.Towers.ToAST.Obby:GetChildren()[156],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[49]:GetChildren()[3],
        workspace.Towers.ToAST.Obby:GetChildren()[120],
        workspace.Towers.ToAST.Obby:GetChildren()[123],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[22].Part,
        workspace.Towers.ToAST.Obby:GetChildren()[131],
        workspace.Towers.ToAST.Obby:GetChildren()[382],
        workspace.Towers.ToAST.Obby:GetChildren()[126],
        workspace.Towers.ToAST.Obby:GetChildren()[127],
        workspace.ClientParts.DistanceAnchoringObjects:GetChildren()[26].Part,
        workspace.Towers.ToAST.Obby:GetChildren()[1019],
        workspace.Towers.ToAST.Obby:GetChildren()[1025],
        workspace.Towers.ToAST.Obby:GetChildren()[936],
        workspace.Towers.ToAST.Obby:GetChildren()[1031],
        workspace.Towers.ToAST.Obby:GetChildren()[224],
        workspace.Towers.ToAST.Obby:GetChildren()[192],

    }
end
