return function()
    return {
        workspace.Towers.ToTS.Obby:GetChildren()[137],
        workspace.Towers.ToTS.Obby:GetChildren()[155],
        workspace.Towers.ToTS.Obby:GetChildren()[156],
        workspace.Towers.ToTS.Obby:GetChildren()[147],
        workspace.Towers.ToTS.Obby:GetChildren()[473],
        workspace.Towers.ToTS.Obby:GetChildren()[441],
        workspace.Towers.ToTS.Obby:GetChildren()[411],
        workspace.Towers.ToTS.Obby:GetChildren()[190],
        workspace.Towers.ToTS.Obby:GetChildren()[532],
        workspace.Towers.ToTS.Obby:GetChildren()[422],
        workspace.Towers.ToTS.Obby:GetChildren()[423],
        workspace.Towers.ToTS.Obby:GetChildren()[531],
        workspace.Towers.ToTS.Obby:GetChildren()[426],
        workspace.Towers.ToTS.Obby:GetChildren()[425],
        workspace.Towers.ToTS.Obby:GetChildren()[409],
        workspace.Towers.ToTS.Obby:GetChildren()[420],
        workspace.Towers.ToTS.Obby:GetChildren()[416],
        workspace.Towers.ToTS.Obby:GetChildren()[415],
        workspace.Towers.ToTS.Obby:GetChildren()[418],
        workspace.Towers.ToTS.Obby:GetChildren()[414],
        workspace.Towers.ToTS.Obby:GetChildren()[424],
        workspace.Towers.ToTS.Obby:GetChildren()[533],
        workspace.Towers.ToTS.Obby:GetChildren()[511],
        workspace.Towers.ToTS.Obby:GetChildren()[547],
        workspace.Towers.ToTS.Obby:GetChildren()[555],
        workspace.Towers.ToTS.Obby:GetChildren()[546],
        workspace.Towers.ToTS.Obby:GetChildren()[510],
        workspace.Towers.ToTS.Obby:GetChildren()[526],
        workspace.Towers.ToTS.Obby:GetChildren()[514],
        workspace.Towers.ToTS.Obby:GetChildren()[539],
        workspace.Towers.ToTS.Obby:GetChildren()[553],
        workspace.Towers.ToTS.Obby:GetChildren()[520],
        workspace.Towers.ToTS.Obby:GetChildren()[500] --F2
    }
end
