local Categories = {
    Ring0 = 9070958509,
    Ring1 = 9070657865,
    Ring2 = 9070979698,
    Ring3 = 9070980083,
    Ring4 = 9070980555,
    Ring5 = 9070980846,
    Ring6 = 9070981164,
    Ring7 = 9070981409,
    Ring9 = 9070982474,
    Zone1 = 9071001075,
    Zone2 = 9071001366,
    Zone3 = 9071001563,
    Zone7 = 9071002677,
    Zone8 = 9071002915,
    Zone9 = 9071004505,
    ["Pit-of-Misery"] = 15639952229,
    ["100M-Event-Replay"] = 115856553162061,
}

return {
    Categories = Categories,
    Towers = {
        --Ring 0
        { name = "TNF",  category = "Ring0", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToG",  category = "Ring0", suggestedTime = { min = "3", sec = "0" } },
        --Ring 1
        { name = "NEAT",  category = "Ring1", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToAST", category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToA",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToM",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToNI",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToH",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToK",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToKY",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToS",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSP",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSP:SE", category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToR",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIE",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoLS",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoLS:SE", category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTS",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIG",  category = "Ring1", suggestedTime = { min = "5", sec = "0" } },
        --Ring 2
        { name = "MAT",  category = "Ring2", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToPS",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToBH",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToOH",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToCH",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToFaF",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToT",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSD",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDD",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTF",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToES",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoWS",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDC",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        --Ring 3
        { name = "ToFT",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIC",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToAT",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDS",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToF",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToWER",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSI",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToWH",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToLD",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToD",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoHaD",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "TAT",  category = "Ring3", suggestedTime = { min = "0", sec = "30" } },
        { name = "ToC",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        --Ring 4
        { name = "ToSH",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToGG",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTM",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToE",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToL",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToLL",  category = "Ring4", suggestedTime = { min = "3", sec = "10" } },
        { name = "WBAT",  category = "Ring4", suggestedTime = { min = "0", sec = "10" } },
        { name = "ToDaD",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToHF",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoU",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToNP",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToCN",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToVS",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToI",  category = "Ring4", suggestedTime = { min = "3", sec = "0" } },
        --Ring 5
        { name = "ToNV",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "LAT",  category = "Ring5", suggestedTime = { min = "0", sec = "10" } },
        { name = "ToTR",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToRS",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDM",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToOC",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToFF",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToEA",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTH",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToGaH",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoCR",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIB",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToFN",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToFO",  category = "Ring5", suggestedTime = { min = "3", sec = "0" } },
        { name = "R14MTR",  category = "Ring5", suggestedTime = { min = "0", sec = "50" } },
        --Ring 6
        { name = "ToFJ",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToEP",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToRR",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTI",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToISC",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToN",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoSR",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIM",  category = "Ring6", suggestedTime = { min = "3", sec = "0" } },
        --Ring 7
        { name = "ToER",  category = "Ring7", suggestedTime = { min = "3", sec = "30" } },
        --Ring 9
        { name = "ToGO",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToBBB",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToQT",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoL",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToPP",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToHA",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToBT",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToCA",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToNS",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToCP",  category = "Ring9", suggestedTime = { min = "3", sec = "0" } },
        --Zone 1
        { name = "SAT",  category = "Zone1", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToZD",  category = "Zone1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTL",  category = "Zone1", suggestedTime = { min = "1", sec = "0" } },
        --Zone 2
        { name = "ToDT",  category = "Zone2", suggestedTime = { min = "5", sec = "0" } },
        --Zone 3
        { name = "ToHH",  category = "Zone3", suggestedTime = { min = "3", sec = "0" } },
        --Zone 7
        { name = "ToFM",  category = "Zone7", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToUA",  category = "Zone7", suggestedTime = { min = "3", sec = "0" } },
        --Zone 8
        { name = "ToDIE",  category = "Zone8", suggestedTime = { min = "3", sec = "0" } },
        --Zone 9
        { name = "ToEMP",  category = "Zone9", suggestedTime = { min = "3", sec = "0" } },
        --Pit of Misery
        { name = "ToMDC",  category = "Pit-of-Misery", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToVH",  category = "Pit-of-Misery", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTRP",  category = "Pit-of-Misery", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToEV",  category = "Pit-of-Misery", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToWM",  category = "Pit-of-Misery", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToBF",  category = "Pit-of-Misery", suggestedTime = { min = "3", sec = "0" } },
        --100M Event Replay
        { name = "100MC",  category = "100M-Event-Replay", suggestedTime = { min = "0", sec = "10" } },
        { name = "100MT",  category = "100M-Event-Replay", suggestedTime = { min = "0", sec = "10" } },
        { name = "100MF",  category = "100M-Event-Replay", suggestedTime = { min = "0", sec = "30" } },
        { name = "100MR",  category = "100M-Event-Replay", suggestedTime = { min = "2", sec = "30" } },
    },
    TowerRush = {
        { name = "R1TR", category = "Ring1", suggestedTime = { min = "39", sec = "0" }, isTowerRush = true, },
        { name = "R5TR", category = "Ring5", suggestedTime = { min = "33", sec = "0" }, isTowerRush = true, },
        { name = "R9TR", category = "Ring9", suggestedTime = { min = "40", sec = "0" }, isTowerRush = true, },
        { name = "PoMTR", category = "Pit-of-Misery", suggestedTime = { min = "200", sec = "0" }, isTowerRush = true, },
    },
}
