local Categories = {
    Ring1 = 9070657865,
    Ring2 = 9070979698,
    Ring3 = 9070980083,
}

return {
    Categories = Categories,
    Towers = {
        { name = "NEAT",  category = "Ring1", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToAST", category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToA",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToM",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToNI",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToH",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToK",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToKY",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToS",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSP",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSP:SE", category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToR",   category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIE",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoLS",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoLS:SE", category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTS",  category = "Ring1", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIG",  category = "Ring1", suggestedTime = { min = "5", sec = "0" } },
        { name = "MAT",  category = "Ring2", suggestedTime = { min = "0", sec = "5" } },
        { name = "ToPS",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToBH",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToOH",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToCH",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToFaF",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToT",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSD",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDD",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToTF",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToES",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "CoWS",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDC",  category = "Ring2", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToFT",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToIC",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToAT",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToDS",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToF",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToWER",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToSI",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToWH",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToLD",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        { name = "ToD",  category = "Ring3", suggestedTime = { min = "3", sec = "0" } },
        
    },
    TowerRush = {
        {
            name        = "R1TR",
            category    = "Ring1",
            suggestedTime = { min = "39", sec = "0" },
            isTowerRush = true,
        },
    },
}
